name: daily-master

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [master]
  #pull_request:
  #  branches: [ main ]

  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - name: Run checkin
        run: |
          python ./codes/main.py
        env:
          USERS_DATA: ${{ secrets.USERS_DATA }}
          USERS_CLOSERS: ${{ secrets.USERS_CLOSERS }}
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
