name: daily-master

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [master]
  #pull_request:
  #  branches: [ main ]

  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: install-chrome
        run: |
          VERSION_STRING="114.0.5735.106"
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - name: Run checkin
        run: |
          python ./codes/main.py
        env:
          USERS_DATA: ${{ secrets.USERS_DATA }}
          USERS_CLOSERS: ${{ secrets.USERS_CLOSERS }}
      # - uses: gautamkrishnar/keepalive-workflow@1.1.0
