name: daily-master

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [master]
  #pull_request:
  #  branches: [ main ]

  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - name: Run checkin
        run: |
          python ./codes/main.py
        env:
          USERS_DATA: ${{ secrets.USERS_DATA }}
          USERS_CLOSERS: ${{ secrets.USERS_CLOSERS }}
      # - uses: gautamkrishnar/keepalive-workflow@1.1.0
