name: workbuddy-checkin

on:
  workflow_dispatch:

  schedule:
    - cron: 0 2 * * *

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - name: Run workbuddy checkin
        run: |
          python -m codes.workbuddy.main
        env:
          WORKBUDDY_DATA: ${{ secrets.WORKBUDDY_DATA }}
          WORKBUDDY_CLOSERS: ${{ secrets.WORKBUDDY_CLOSERS }}
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
